import type { OptionIR, OptionPath, OptionScope, OptionTypeIR } from "./ir.ts";

export interface GenerateOptionTypesOptions {
  readonly importPath: string;
  readonly options: readonly OptionIR[];
  readonly rootTypeName: string;
  readonly scope: OptionScope;
}

export interface GenerateOptionTypeFileOptions {
  readonly fixtureScope?: string;
  readonly importPath: string;
  readonly roots: readonly OptionTypeRoot[];
  readonly options: readonly OptionIR[];
}

export interface OptionTypeRoot {
  readonly rootTypeName: string;
  readonly scope: OptionScope;
}

interface OptionTree {
  readonly children: Map<string, OptionTree>;
  option?: OptionIR;
}

export const generateOptionTypes = (options: GenerateOptionTypesOptions): string => {
  const body = renderRootInterface(options.rootTypeName, options.scope, options.options);

  return `${renderGeneratedHeader()}
import type { NixExpr, NixInput, UnsupportedNixOptionExpr } from ${JSON.stringify(options.importPath)};

${renderSharedTypes()}

${body}
`;
};

export const generateOptionTypeFile = (options: GenerateOptionTypeFileOptions): string => {
  const interfaces = options.roots
    .map((root) => renderRootInterface(root.rootTypeName, root.scope, options.options))
    .join("\n\n");

  return `${renderGeneratedHeader(options.fixtureScope)}
import type { NixExpr, NixInput, UnsupportedNixOptionExpr } from ${JSON.stringify(options.importPath)};

${renderSharedTypes()}

${interfaces}

${renderRootNamespaces(options.roots)}

${renderUnsupportedMetadata(options.options)}
`;
};

const renderRootInterface = (
  rootTypeName: string,
  scope: OptionScope,
  options: readonly OptionIR[],
): string => {
  const tree = buildOptionTree(
    options.filter((option) => option.scope === scope).map((option) => option),
  );

  return `export interface ${rootTypeName} ${renderTree(tree, 0)}`;
};

const renderGeneratedHeader = (fixtureScope?: string): string => {
  const lines = ["// Generated by Typeflake from real Nix option metadata."];
  if (fixtureScope !== undefined) lines.push(`// Fixture scope: ${fixtureScope}`);

  return lines.join("\n");
};

const renderSharedTypes = (): string => `export type NixOptionValue<T> = T | NixExpr;

export type UnsupportedNixOption<Description extends string> =
  UnsupportedNixOptionExpr<Description>;`;

const buildOptionTree = (options: readonly OptionIR[]): OptionTree => {
  const root = createTree();

  for (const option of options) {
    insertOption(root, option.path, option);
  }

  return root;
};

const createTree = (): OptionTree => ({ children: new Map() });

const insertOption = (root: OptionTree, path: OptionPath, option: OptionIR): void => {
  let current = root;

  for (const segment of path) {
    const existing = current.children.get(segment);
    if (existing !== undefined) {
      current = existing;
    } else {
      const next = createTree();
      current.children.set(segment, next);
      current = next;
    }
  }

  current.option = option;
};

const renderTree = (tree: OptionTree, depth: number): string => {
  const entries = [...tree.children.entries()].toSorted(([left], [right]) =>
    left.localeCompare(right),
  );

  if (entries.length === 0) {
    return tree.option === undefined ? "{}" : toOptionValueType(tree.option);
  }

  const pad = indentation(depth);
  const rendered = entries.map(([key, child]) => renderTreeEntry(key, child, depth + 1)).join("\n");

  return `{\n${rendered}\n${pad}}`;
};

const renderTreeEntry = (key: string, child: OptionTree, depth: number): string => {
  const childPad = indentation(depth);
  const optionComment = child.children.size === 0 ? renderOptionComment(child.option, depth) : "";

  return `${optionComment}${childPad}readonly ${quoteProperty(key)}?: ${renderTree(child, depth)};`;
};

const toOptionValueType = (option: OptionIR): string => {
  const optionType = toTypeScriptType(option.type, option.path);
  return optionType.startsWith("UnsupportedNixOption<")
    ? optionType
    : `NixOptionValue<${optionType}>`;
};

export const toTypeScriptType = (nixType: OptionTypeIR, path: readonly string[] = []): string => {
  const normalized = normalizeTypeName(nixType.name);
  const description = nixType.description?.toLowerCase() ?? "";

  if (normalized === "bool" || normalized === "boolean") return "boolean";
  if (normalized === "nullor") return renderNullableType(nixType, path);
  if (normalized === "listof") return renderListType(nixType, path);
  if (normalized === "attrsof") return renderAttrsType(nixType, path);
  if (normalized === "enum") return renderEnumType(nixType) ?? "string";
  if (normalized === "str" || normalized === "string" || normalized.startsWith("strmatching")) {
    return "string";
  }
  if (isNumberType(normalized, description)) return "number";
  if (normalized === "package") return "NixInput";
  if (normalized === "path") return "string";
  if (normalized === "submodule") return "NixInput";

  if (description.includes("list of package")) return "readonly NixInput[]";
  if (description.includes("list of string")) return "readonly string[]";
  if (description.includes("attribute set")) return "Readonly<Record<string, NixInput>>";

  return unsupportedType(nixType);
};

export const collectUnsupportedOptions = (options: readonly OptionIR[]): readonly OptionIR[] =>
  options.filter((option) => toTypeScriptType(option.type, option.path).startsWith("Unsupported"));

const renderNullableType = (nixType: OptionTypeIR, path: readonly string[]): string => {
  const nested = nixType.nestedTypes.elemType ?? nixType.nestedTypes.valueType;
  if (nested === undefined) return `${unsupportedType(nixType)} | null`;

  return `${toTypeScriptType(nested, path)} | null`;
};

const renderListType = (nixType: OptionTypeIR, path: readonly string[]): string => {
  const elemType = nixType.nestedTypes.elemType;
  if (elemType === undefined) return "readonly NixInput[]";

  return `readonly ${toCollectionElementType(elemType, path)}[]`;
};

const renderAttrsType = (nixType: OptionTypeIR, path: readonly string[]): string => {
  const elemType = nixType.nestedTypes.elemType;
  if (elemType === undefined) return "Readonly<Record<string, NixInput>>";

  return `Readonly<Record<string, ${toCollectionElementType(elemType, path)}>>`;
};

const toCollectionElementType = (nixType: OptionTypeIR, path: readonly string[]): string => {
  const normalized = normalizeTypeName(nixType.name);
  if (normalized === "submodule") return "NixInput";

  return toTypeScriptType(nixType, path);
};

const isNumberType = (normalized: string, description: string): boolean =>
  normalized.includes("int") ||
  normalized === "number" ||
  description.includes("integer") ||
  description.includes("signed integer");

const unsupportedType = (nixType: OptionTypeIR): string =>
  `UnsupportedNixOption<${JSON.stringify(renderUnsupportedDescription(nixType))}>`;

const renderUnsupportedDescription = (nixType: OptionTypeIR): string =>
  nixType.description === null ? nixType.name : `${nixType.name}: ${nixType.description}`;

const normalizeTypeName = (name: string): string => name.toLowerCase().replaceAll(/[^a-z0-9]/g, "");

const quoteProperty = (key: string): string =>
  /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key);

const indentation = (depth: number): string => "  ".repeat(depth);

const renderRootNamespaces = (roots: readonly OptionTypeRoot[]): string =>
  roots.map(renderRootNamespace).join("\n\n");

const renderRootNamespace = (root: OptionTypeRoot): string => `export namespace ${namespaceName(
  root,
)} {
  export type Config = ${root.rootTypeName};
}`;

const namespaceName = (root: OptionTypeRoot): string => {
  switch (root.scope) {
    case "home-manager":
      return "HomeManagerOptions";
    case "nixos":
      return "NixOSOptions";
    default:
      root.scope satisfies never;
      return `${root.rootTypeName}Options`;
  }
};

const renderUnsupportedMetadata = (options: readonly OptionIR[]): string => {
  const unsupported = collectUnsupportedOptions(options);
  if (unsupported.length === 0) return "export const unsupportedNixOptions = [] as const;";

  const entries = unsupported.map(
    (option) => `  {
    scope: ${JSON.stringify(option.scope)},
    path: ${JSON.stringify(option.path.join("."))},
    type: ${JSON.stringify(option.type.name)},
    description: ${JSON.stringify(renderUnsupportedDescription(option.type))},
  },`,
  );

  return `export const unsupportedNixOptions = [
${entries.join("\n")}
] as const;`;
};

const renderOptionComment = (option: OptionIR | undefined, depth: number): string => {
  if (option === undefined) return "";

  const lines = [
    option.description,
    option.defaultText === null ? null : `Default: ${option.defaultText}`,
    option.exampleText === null ? null : `Example: ${option.exampleText}`,
  ].flatMap((line) => (line === null ? [] : [sanitizeCommentLine(line)]));

  if (lines.length === 0) return "";

  const pad = indentation(depth);

  return `${pad}/**\n${lines.map((line) => `${pad} * ${line}`).join("\n")}\n${pad} */\n`;
};

const sanitizeCommentLine = (line: string): string => {
  const withoutTerminators = line.replaceAll("*/", "* /").replaceAll(/\s+/g, " ").trim();
  return withoutTerminators.length > 160
    ? `${withoutTerminators.slice(0, 157).trimEnd()}...`
    : withoutTerminators;
};

const renderEnumType = (nixType: OptionTypeIR): string | undefined => {
  const literals = enumLiterals(nixType.description);
  if (literals.length === 0) return undefined;
  if (literals.length > 6) {
    return `\n${literals.map((literal) => `      | ${JSON.stringify(literal)}`).join("\n")}\n    `;
  }

  return literals.map((literal) => JSON.stringify(literal)).join(" | ");
};

const enumLiterals = (description: string | null): readonly string[] => {
  if (description === null) return [];

  return [...description.matchAll(/"((?:\\.|[^"\\])*)"/g)].flatMap((match) => {
    const [, literal] = match;
    if (literal === undefined) return [];

    return [literal.replaceAll('\\"', '"')];
  });
};
