import type { OptionIR, OptionPath, OptionScope } from "./ir.ts";

export interface GenerateOptionTypesOptions {
  readonly importPath: string;
  readonly options: readonly OptionIR[];
  readonly rootTypeName: string;
  readonly scope: OptionScope;
}

export interface GenerateOptionTypeFileOptions {
  readonly fixtureScope?: string;
  readonly importPath: string;
  readonly roots: readonly OptionTypeRoot[];
  readonly options: readonly OptionIR[];
}

export interface OptionTypeRoot {
  readonly rootTypeName: string;
  readonly scope: OptionScope;
}

interface OptionTree {
  readonly children: Map<string, OptionTree>;
  option?: OptionIR;
}

export const generateOptionTypes = (options: GenerateOptionTypesOptions): string => {
  const body = renderRootInterface(options.rootTypeName, options.scope, options.options);

  return `${renderGeneratedHeader()}
import type { NixExpr, NixInput } from ${JSON.stringify(options.importPath)};

${renderSharedTypes()}

${body}
`;
};

export const generateOptionTypeFile = (options: GenerateOptionTypeFileOptions): string => {
  const interfaces = options.roots
    .map((root) => renderRootInterface(root.rootTypeName, root.scope, options.options))
    .join("\n\n");

  return `${renderGeneratedHeader(options.fixtureScope)}
import type { NixExpr, NixInput } from ${JSON.stringify(options.importPath)};

${renderSharedTypes()}

${interfaces}
`;
};

const renderRootInterface = (
  rootTypeName: string,
  scope: OptionScope,
  options: readonly OptionIR[],
): string => {
  const tree = buildOptionTree(
    options.filter((option) => option.scope === scope).map((option) => option),
  );

  return `export interface ${rootTypeName} ${renderTree(tree, 0)}`;
};

const renderGeneratedHeader = (fixtureScope?: string): string => {
  const lines = ["// Generated by Typeflake from real Nix option metadata."];
  if (fixtureScope !== undefined) lines.push(`// Fixture scope: ${fixtureScope}`);

  return lines.join("\n");
};

const renderSharedTypes = (): string => `export type NixOptionValue<T> = T | NixExpr;

export type UnsupportedNixOption<Description extends string> = NixExpr<"unsupported"> & {
  readonly __unsupportedNixOption: Description;
};`;

const buildOptionTree = (options: readonly OptionIR[]): OptionTree => {
  const root = createTree();

  for (const option of options) {
    insertOption(root, option.path, option);
  }

  return root;
};

const createTree = (): OptionTree => ({ children: new Map() });

const insertOption = (root: OptionTree, path: OptionPath, option: OptionIR): void => {
  let current = root;

  for (const segment of path) {
    const existing = current.children.get(segment);
    if (existing !== undefined) {
      current = existing;
    } else {
      const next = createTree();
      current.children.set(segment, next);
      current = next;
    }
  }

  current.option = option;
};

const renderTree = (tree: OptionTree, depth: number): string => {
  const entries = [...tree.children.entries()].toSorted(([left], [right]) =>
    left.localeCompare(right),
  );

  if (entries.length === 0) {
    return tree.option === undefined ? "{}" : toOptionValueType(tree.option);
  }

  const pad = indentation(depth);
  const childPad = indentation(depth + 1);
  const rendered = entries
    .map(
      ([key, child]) =>
        `${childPad}readonly ${quoteProperty(key)}?: ${renderTree(child, depth + 1)};`,
    )
    .join("\n");

  return `{\n${rendered}\n${pad}}`;
};

const toOptionValueType = (option: OptionIR): string =>
  `NixOptionValue<${toTypeScriptType(option.type, option.path)}>`;

export const toTypeScriptType = (nixType: string, path: readonly string[] = []): string => {
  const normalized = nixType.toLowerCase();

  if (normalized === "boolean" || normalized === "bool") return "boolean";
  if (normalized === "enum" || normalized === "string" || normalized === "str") return "string";
  if (normalized.includes("list") && normalized.includes("package")) {
    return "readonly NixInput[]";
  }
  if (normalized.includes("list") && normalized.includes("string")) {
    return "readonly string[]";
  }
  if (normalized === "listof" && path.join(".") === "environment.systemPackages") {
    return "readonly NixInput[]";
  }
  if (normalized === "listof") return "readonly string[]";
  if (normalized.includes("attribute set")) {
    return "Readonly<Record<string, NixInput>>";
  }
  if (normalized === "attrsof") return "Readonly<Record<string, NixInput>>";

  return `UnsupportedNixOption<${JSON.stringify(nixType)}>`;
};

const quoteProperty = (key: string): string =>
  /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key);

const indentation = (depth: number): string => "  ".repeat(depth);
