import * as Effect from "effect/Effect";
import { nixExpr, rawNix, renderAttrName, type NixExpr, type NixInput } from "./nix/expr.ts";
import { renderNixValue } from "./nix/render.ts";

export interface FlakeInput<Name extends string = string> extends NixExpr<"input"> {
  readonly name: Name;
  readonly url: string;
}

export type FlakeInputSpec = FlakeInput;

export type FlakeInputs = Readonly<Record<string, FlakeInput>>;

export type NamedFlakeInputs<Inputs extends FlakeInputs> = {
  readonly [Name in keyof Inputs & string]: FlakeInput<Name>;
};

export type CheckedFlakeInputs<Inputs extends FlakeInputs> = Inputs & NamedFlakeInputs<Inputs>;

export interface DevShell {
  readonly packages?: readonly NixInput[];
}

export interface FlakeOutputs {
  readonly nixosConfigurations?: Record<string, NixInput>;
  readonly devShells?: Record<string, Record<string, DevShell>>;
}

export interface FlakeSpec<Inputs extends FlakeInputs = FlakeInputs> {
  readonly description?: string;
  readonly inputs: CheckedFlakeInputs<Inputs>;
  readonly outputs: (inputs: CheckedFlakeInputs<Inputs>) => FlakeOutputs;
}

export type FlakeTaint = "effect" | "impure" | "pure";

export interface TypeflakeFlake<
  Inputs extends FlakeInputs = FlakeInputs,
  Taint extends FlakeTaint = "pure",
  E = never,
  R = never,
> {
  readonly taint: Taint;
  readonly spec: Effect.Effect<FlakeSpec<Inputs>, E, R>;
}

export type AnyTypeflakeFlake = TypeflakeFlake<FlakeInputs, FlakeTaint, unknown, unknown>;

export interface FlakeModule {
  readonly default: AnyTypeflakeFlake;
}

export const Flake = {
  input<const Name extends string>(name: Name, url: string): FlakeInput<Name> {
    return {
      ...nixExpr("input", renderAttrName(name)),
      name,
      url,
    };
  },

  inputs<const Inputs extends FlakeInputs>(
    inputs: CheckedFlakeInputs<Inputs>,
  ): CheckedFlakeInputs<Inputs> {
    return inputs;
  },

  make<const Inputs extends FlakeInputs>(spec: FlakeSpec<Inputs>): TypeflakeFlake<Inputs> {
    return {
      taint: "pure",
      spec: Effect.succeed(spec),
    };
  },

  effect<const Inputs extends FlakeInputs, E, R>(
    spec: Effect.Effect<FlakeSpec<Inputs>, E, R>,
  ): TypeflakeFlake<Inputs, "effect", E, R> {
    return { spec, taint: "effect" };
  },

  impure<const Inputs extends FlakeInputs, E, R>(
    spec: Effect.Effect<FlakeSpec<Inputs>, E, R>,
  ): TypeflakeFlake<Inputs, "impure", E, R> {
    return { spec, taint: "impure" };
  },
};

export const resolveFlakeSpec = <Inputs extends FlakeInputs, Taint extends FlakeTaint, E, R>(
  flake: TypeflakeFlake<Inputs, Taint, E, R>,
): Effect.Effect<FlakeSpec<Inputs>, E, R> => flake.spec;

export const renderFlake = (spec: FlakeSpec): string => {
  const outputs = spec.outputs(spec.inputs);

  return `${renderNixValue({
    description: spec.description ?? "Generated by Typeflake",
    inputs: renderInputs(spec.inputs),
    outputs: rawNix(renderOutputs(spec.inputs, outputs)),
  })}\n`;
};

const renderInputs = (inputs: FlakeInputs): NixInput =>
  Object.fromEntries(
    Object.entries(inputs).map(([name, input]) => [
      name,
      {
        url: input.url,
      },
    ]),
  );

const renderOutputs = (inputs: FlakeInputs, outputs: FlakeOutputs): string => {
  const args = ["self", ...Object.keys(inputs)].join(", ");
  const body = renderNixValue({
    devShells: outputs.devShells === undefined ? undefined : renderDevShells(outputs.devShells),
    nixosConfigurations: outputs.nixosConfigurations,
  });

  return `{ ${args} }: ${body}`;
};

const renderDevShells = (systems: Record<string, Record<string, DevShell>>): NixInput =>
  Object.fromEntries(
    Object.entries(systems).map(([system, shells]) => [
      system,
      Object.fromEntries(
        Object.entries(shells).map(([name, shell]) => [
          name,
          rawNix(
            `let pkgs = nixpkgs.legacyPackages.${renderAttrName(system)}; in pkgs.mkShell ${renderNixValue(
              {
                packages: shell.packages ?? [],
              },
            )}`,
          ),
        ]),
      ),
    ]),
  );
