import * as Effect from "effect/Effect";
import { nixExpr, rawNix, renderAttrName, type NixExpr, type NixValue } from "./nix/expr.ts";
import { renderNixValue } from "./nix/render.ts";

export interface FlakeInput {
  readonly url: string;
}

export type FlakeInputSpec = string | FlakeInput;

export type FlakeInputRefs<Inputs extends Record<string, FlakeInputSpec>> = Readonly<
  Record<keyof Inputs & string, NixExpr<"input">>
>;

export interface DevShell {
  readonly packages?: readonly NixValue[];
}

export interface FlakeOutputs {
  readonly nixosConfigurations?: Record<string, NixValue>;
  readonly devShells?: Record<string, Record<string, DevShell>>;
}

export interface FlakeSpec<
  Inputs extends Record<string, FlakeInputSpec> = Record<string, FlakeInputSpec>,
> {
  readonly description?: string;
  readonly inputs: Inputs;
  readonly outputs: (inputs: FlakeInputRefs<Inputs>) => FlakeOutputs;
}

export interface TypeflakeFlake<
  Inputs extends Record<string, FlakeInputSpec> = Record<string, FlakeInputSpec>,
  E = never,
  R = never,
> {
  readonly spec: Effect.Effect<FlakeSpec<Inputs>, E, R>;
}

export type AnyTypeflakeFlake = TypeflakeFlake<Record<string, FlakeInputSpec>, unknown, unknown>;

export interface FlakeModule {
  readonly default: AnyTypeflakeFlake;
}

export const Flake = {
  make<const Inputs extends Record<string, FlakeInputSpec>>(
    spec: FlakeSpec<Inputs>,
  ): TypeflakeFlake<Inputs> {
    return {
      spec: Effect.succeed(spec),
    };
  },

  effect<const Inputs extends Record<string, FlakeInputSpec>, E, R>(
    spec: Effect.Effect<FlakeSpec<Inputs>, E, R>,
  ): TypeflakeFlake<Inputs, E, R> {
    return { spec };
  },
};

export const resolveFlakeSpec = <Inputs extends Record<string, FlakeInputSpec>, E, R>(
  flake: TypeflakeFlake<Inputs, E, R>,
): Effect.Effect<FlakeSpec<Inputs>, E, R> => flake.spec;

export const renderFlake = (spec: FlakeSpec): string => {
  const inputRefs = createInputRefs(spec.inputs);
  const outputs = spec.outputs(inputRefs);

  return `${renderNixValue({
    description: spec.description ?? "Generated by Typeflake",
    inputs: renderInputs(spec.inputs),
    outputs: rawNix(renderOutputs(spec.inputs, outputs)),
  })}\n`;
};

const renderInputs = (inputs: Record<string, FlakeInputSpec>): NixValue =>
  Object.fromEntries(
    Object.entries(inputs).map(([name, input]) => [
      name,
      {
        url: typeof input === "string" ? input : input.url,
      },
    ]),
  );

const renderOutputs = (inputs: Record<string, FlakeInputSpec>, outputs: FlakeOutputs): string => {
  const args = ["self", ...Object.keys(inputs)].join(", ");
  const body = renderNixValue(
    {
      devShells: outputs.devShells === undefined ? undefined : renderDevShells(outputs.devShells),
      nixosConfigurations: outputs.nixosConfigurations,
    },
    { indent: 1 },
  );

  return `{ ${args} }: ${body}`;
};

const renderDevShells = (systems: Record<string, Record<string, DevShell>>): NixValue =>
  Object.fromEntries(
    Object.entries(systems).map(([system, shells]) => [
      system,
      Object.fromEntries(
        Object.entries(shells).map(([name, shell]) => [
          name,
          rawNix(
            `let pkgs = nixpkgs.legacyPackages.${renderAttrName(system)}; in pkgs.mkShell ${renderNixValue(
              {
                packages: shell.packages ?? [],
              },
            )}`,
          ),
        ]),
      ),
    ]),
  );

const createInputRefs = <Inputs extends Record<string, FlakeInputSpec>>(
  inputs: Inputs,
): FlakeInputRefs<Inputs> => {
  const refs: Record<string, NixExpr<"input">> = {};

  for (const name of Object.keys(inputs)) {
    refs[name] = nixExpr("input", renderAttrName(name));
  }

  // oxlint-disable-next-line typescript/no-unsafe-type-assertion -- Object.keys(inputs) is the runtime witness for keyof Inputs.
  return refs as FlakeInputRefs<Inputs>;
};
