import * as Effect from "effect/Effect";
import { rawNix, renderAttrName, type NixExpr, type NixValue } from "./nix/expr.ts";
import { renderNixValue } from "./nix/render.ts";

const typeflakeFlakeSymbol: unique symbol = Symbol.for(
  "typeflake.flake",
) as typeof typeflakeFlakeSymbol;

export interface FlakeInput {
  readonly url: string;
}

export type FlakeInputSpec = string | FlakeInput;

export type FlakeInputRefs<Inputs extends Record<string, FlakeInputSpec>> = {
  readonly [Name in keyof Inputs]: NixExpr<"input">;
};

export interface DevShell {
  readonly packages?: readonly NixValue[];
}

export interface FlakeOutputs {
  readonly nixosConfigurations?: Record<string, NixValue>;
  readonly devShells?: Record<string, Record<string, DevShell>>;
}

export interface FlakeSpec<
  Inputs extends Record<string, FlakeInputSpec> = Record<string, FlakeInputSpec>,
> {
  readonly description?: string;
  readonly inputs: Inputs;
  readonly outputs: (inputs: FlakeInputRefs<Inputs>) => FlakeOutputs;
}

export interface TypeflakeFlake<
  Inputs extends Record<string, FlakeInputSpec> = Record<string, FlakeInputSpec>,
> {
  readonly [typeflakeFlakeSymbol]: true;
  readonly resolve: () => Promise<FlakeSpec<Inputs>>;
}

export type FlakeProgram<Inputs extends Record<string, FlakeInputSpec>> =
  | FlakeSpec<Inputs>
  | Effect.Effect<FlakeSpec<Inputs>>;

export const Flake = {
  make<const Inputs extends Record<string, FlakeInputSpec>>(
    program: FlakeProgram<Inputs>,
  ): TypeflakeFlake<Inputs> {
    return {
      [typeflakeFlakeSymbol]: true,
      resolve: async () => (Effect.isEffect(program) ? Effect.runPromise(program) : program),
    };
  },
};

export const isTypeflakeFlake = (value: unknown): value is TypeflakeFlake =>
  typeof value === "object" &&
  value !== null &&
  typeflakeFlakeSymbol in value &&
  (value as TypeflakeFlake)[typeflakeFlakeSymbol] === true;

export const resolveFlakeSpec = async (value: unknown): Promise<FlakeSpec> => {
  if (isTypeflakeFlake(value)) return value.resolve();
  if (Effect.isEffect(value)) return Effect.runPromise(value as Effect.Effect<FlakeSpec>);
  if (isFlakeSpec(value)) return value;
  throw new Error(
    "Expected default export to be Flake.make(...), an Effect<FlakeSpec>, or a FlakeSpec object",
  );
};

export const renderFlake = (spec: FlakeSpec): string => {
  const inputRefs = createInputRefs(spec.inputs);
  const outputs = spec.outputs(inputRefs);

  return `${renderNixValue({
    description: spec.description ?? "Generated by Typeflake",
    inputs: renderInputs(spec.inputs),
    outputs: rawNix(renderOutputs(spec.inputs, outputs)),
  })}\n`;
};

const renderInputs = (inputs: Record<string, FlakeInputSpec>): NixValue =>
  Object.fromEntries(
    Object.entries(inputs).map(([name, input]) => [
      name,
      {
        url: typeof input === "string" ? input : input.url,
      },
    ]),
  );

const renderOutputs = (inputs: Record<string, FlakeInputSpec>, outputs: FlakeOutputs): string => {
  const args = ["self", ...Object.keys(inputs)].join(", ");
  const body = renderNixValue(
    {
      devShells: outputs.devShells === undefined ? undefined : renderDevShells(outputs.devShells),
      nixosConfigurations: outputs.nixosConfigurations,
    },
    { indent: 1 },
  );

  return `{ ${args} }: ${body}`;
};

const renderDevShells = (systems: Record<string, Record<string, DevShell>>): NixValue =>
  Object.fromEntries(
    Object.entries(systems).map(([system, shells]) => [
      system,
      Object.fromEntries(
        Object.entries(shells).map(([name, shell]) => [
          name,
          rawNix(
            `let pkgs = nixpkgs.legacyPackages.${renderAttrName(system)}; in pkgs.mkShell ${renderNixValue(
              {
                packages: shell.packages ?? [],
              },
            )}`,
          ),
        ]),
      ),
    ]),
  );

const createInputRefs = <Inputs extends Record<string, FlakeInputSpec>>(
  inputs: Inputs,
): FlakeInputRefs<Inputs> =>
  Object.fromEntries(
    Object.keys(inputs).map((name) => [name, rawNix<NixExpr<"input">>(renderAttrName(name))]),
  ) as unknown as FlakeInputRefs<Inputs>;

const isFlakeSpec = (value: unknown): value is FlakeSpec =>
  typeof value === "object" &&
  value !== null &&
  "inputs" in value &&
  "outputs" in value &&
  typeof (value as FlakeSpec).outputs === "function";
